---
- name: Play to setup app servers
  hosts: apps
  become: true

  tasks:
  - name: Install & configure firewall
    include_role:
      name: firewall
    vars:
      firewall_services:
      - http
      firewall_tcp_ports:
      - 8080

  - name: Install & configure flask app
    include_role:
      name: flask
