- name: Play to execute end to end smoke test
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Gather LB server info from OpenStack
    os_server_info:
      server: "{{ groups.frontends[0] }}" 
    register: r_frontends

  - name: Liveness probe of LB and app
    uri:
      url: "http://{{ r_frontends.openstack_servers[0].private_v4 }}/ping"
      method: GET
      return_content: yes
    until: '"alive" in result.content'
    delay: 1
    register: result

  - name: Gather DB server info from OpenStack
    os_server_info:
      server: "{{ groups.appdbs[0] }}"
    register: r_appdbs

  - name: Liveness probe of Postgres DB
    postgresql_ping:
      db: flask_db
      login_host: "{{ r_appdbs.openstack_servers[0].private_v4 }}"
      login_user: flask
      login_password: redhat
      ssl_mode: disable
    delegate_to: "{{ groups.apps[0] }}"
